name: Build deployment image

on:
  workflow_dispatch:

jobs:
  build-images:
    name: Build deployment image and push image tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker buildx build
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deployment image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: deploy/webapp/webapp-deploy.dockerfile
          tags:
            ghcr.io/${{ github.repository }}/webapp-deploy:latest
          build-args:
            WEBAPP_DOCKER_IMAGE=ghcr.io/${{ github.repository }}/webapp-base:latest
            ARTIFACTS_DOCKER_IMAGE=ghcr.io/${{ github.repository }}/artifacts:latest
            GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
