name: Build artifacts image

on:
  workflow_dispatch:

jobs:
  build-images:
    name: Build artifacts image and push image tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker buildx build
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifacts image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: deploy/artifacts/prepare-artifacts.dockerfile
          tags:
            ghcr.io/${{ github.repository }}/artifacts:latest
          build-args:
            WEBAPP_DOCKER_IMAGE=ghcr.io/${{ github.repository }}/webapp-base:latest
          push: true
