name: Build search indexer image

on:
  workflow_dispatch:

jobs:
  build-images:
    name: Build search indexer image and push image tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker buildx build
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Push to gcr.io and rebuild the search index
      - name: Build search indexer image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: deploy/search-index/search-index.dockerfile
          tags:
            ghcr.io/${{ github.repository }}/indexer:latest
          build-args: |
            WEBAPP_DEPLOY_DOCKER_IMAGE=ghcr.io/${{ github.repository }}/webapp-deploy:latest
          push: true
