name: Reindex content

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Tag to use for the search indexer image'
        required: true
        default: latest

jobs:
  reindex-content:
    name: Reindex content in ElasticSearch
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate with Google
      id: 'google-auth'
      uses: 'google-github-actions/auth@v0.4.4'
      with:
        # added via the sv-github-actions-sa Service Account
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: 'access_token'
    - name: Login to GitHub and GCR container registries
      run: |
        echo '${{ github.token }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
        echo '${{ steps.google-auth.outputs.access_token }}' | docker login gcr.io -u oauth2accesstoken --password-stdin
    - name: Tag and push GCR image
      run: |
        docker pull ghcr.io/${{ github.repository }}/indexer:${{ github.event.inputs.imageTag }}
        docker tag ghcr.io/${{ github.repository }}/indexer:${{ github.event.inputs.imageTag }} gcr.io/${{ github.repository }}/indexer:${{ github.event.inputs.imageTag }}
        docker push gcr.io/${{ github.repository }}/indexer:${{ github.event.inputs.imageTag }}
